name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          mkdir -p results
          # Force Chrome to run headless with unique user data dir
          export ROBOT_BROWSER_OPTIONS="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --disable-extensions --remote-debugging-port=9222 --user-data-dir=$(mktemp -d)"
          robot --variable BROWSER_OPTIONS:"$ROBOT_BROWSER_OPTIONS" --outputdir results tests/ || true

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: results/
